// Generated by Selenium IDE
const { Builder, By, Key, until, Capabilities } = require('selenium-webdriver')
const assert = require('assert')

describe('IMBD', function() {
  this.timeout(60000)
  let driver
  let vars
  let capabilities = new Capabilities().setBrowserName("chrome");
  beforeEach(async function() {
    driver = await new Builder()
             .usingServer("http://localhost:4444/wd/hub")
             .withCapabilities(capabilities)
             .build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('IMBD', async function() {
    await driver.get("https://www.imdb.com/")
    await driver.manage().window().setRect(729, 698)
    await driver.findElement(By.id("suggestion-search")).click()
    await driver.findElement(By.id("suggestion-search")).sendKeys("wandavision")
    await driver.findElement(By.id("suggestion-search")).sendKeys(Key.ENTER)
    //await driver.findElement(By.linkText("WandaVision")).click()
  })
})
